# Generated by Django 4.1.10 on 2023-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('publish_date', models.DateField()),
                ('todays', models.BooleanField(default=False)),
            ],
        ),
    ]
